name: Validate and Format
run-name: "${{ github.actor }} pushed to ${{ github.ref }}"
on:
  pull_request:
    branches: 
       - main
permissions:
  contents: write
jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: repo
      - name: Checkout ash repo
        uses: actions/checkout@v4
        with:
          repository: jasonend/automated-security-helper
          path: tools
      - name: ASH scan
        run: |
          tools/ash --quiet --force --source-dir /repo --output-dir .
          cat aggregated_results.txt
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ash-report
          path: aggregated_results.txt
  format:
    needs: scan
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.5.0
      - name: Terraform update, format and validate
        working-directory: ./terraform
        run: |
          cp ../samples/proxy-config.yaml ../config/proxy-config.yaml
          cp ../samples/vars.yaml ../config/proxy-config.yaml
          terraform init -upgrade
          terraform validate
      - name: Update terraform documentation
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0
        with:
          working-dir: ./terraform
          output-file: README.md
          output-method: replace
      - name: CDK format and lint
        working-directory: ./cdk
        run: |
          npm install
          npm run format
          npm run lint
      - name: Commit automated formatting
        run: |
          if ! git status | grep -e '^nothing to commit, working tree clean'; then 
            git config --global user.name "$github.actor"
            git config --global user.email "$github.actor@users.noreply.github.com"
            sudo git add .
            git commit -m "Automated format updates."
            git push
          fi
